### PR TITLE
setup NightWatch

### PR DESCRIPTION
**Pull request by rickbacci**
@joshcheek, @selfup, @jbrr

To answer your question Jeff. I setup Nightwatch. Seems pretty straightforward.

### CODE REVIEW

**Comment by rickbacci** [comment]
Going to write a feature test to cover features to this point.

Net PR will be to allow users to vote.

**Comment by jbrr** [comment]
Nice, that seems cool, I might use that too if it works well for you.

**Comment by rickbacci** [comment]
https://www.dropbox.com/s/ie6ofwt0885r88e/Screenshot%202016-01-16%2019.58.57.png?dl=0

@joshcheek, @selfup, @jbrr, @rrgayhart

Spent a bit too long on this, but it works. I am having a problem with iterating over the array of choices in jade. It looks like it is a string when it gets to jade, but it is an array when it is in server.js

pic shows whats happening

**Comment by jbrr** [comment]
That's really strange. I just cloned it, I'm going to poke around a little bit.

**Comment by rickbacci** [comment]
yeah, its wierd. if i just put an array in jade it works fine. It looks like a string is what is showing up in jade for some reason.

**Comment by rickbacci** [comment]
https://www.dropbox.com/s/2my6xx3gz31usqn/Screenshot%202016-01-16%2020.57.52.png?dl=0

this is what is happening in pry.js

never seen duplicate chars before, but i just started using it. @jbrr

**Comment by jbrr** [comment]
I think it's an issue with Redis, I don't know very much about Redis, maybe someone else who's tagged here can help, but I think you need to store arrays in a special way, like as a set or a list or something?

**Comment by jbrr** [comment]
Or maybe when you retrieve it from Redis, you can like split on commas or something and make it back into an array? I'm not totally sure how to do that in JS, but it seems doable.

**Comment by rickbacci** [comment]
i'm not sure about that, i'm pretty sure i'm storing stuff in a hash, but i'm not sure.
@stevekinney  Steve you have any idea about this?

**Comment by jbrr** [comment]
Well, when you're trying to store `poll.choices`, which comes in as an array through the POST request, I don't think it gets stored in Redis as an array, I think Redis stores it as a string. That's all I can figure, I can't see what else would be causing that.

**Comment by rickbacci** [comment]
@jbrr I just checked in the show page and it is a string at that point. I'm going to try to use lodash to split it

**Comment by stevekinney** [comment]
Yea, it's a string. So, `each` splits it out by character.

``` js
{ pollType: 'Awesome Poll',
  status: 'open',
  adminString: '1d73c3253e0281f18e79',
  voterString: '329ef250fd567855cd41',
  question: 'Wowow',
  choices: 'hehe,lolol,coolcoolcool,poooooo',
  endTime: '' }
```

**Comment by rickbacci** [comment]
@stevekinney ok so i'm thinking i just use lodash to turn it back into an array, but when i require it in server.js it's not working right. Any ideas what to check?

**Comment by stevekinney** [comment]
I mean you don't really need Lo-Dash if you're not otherwise using it.

``` js
poll.choices = poll.choices.split(',');
```

Food for thought, if you abstract all of your getting and setting, then you can just have this be part of the process of fetching something from the database.

**Comment by rickbacci** [comment]
@stevekinney That got it. I figure i need lodash a bit down the line, but for now i'll just move on.  thanks :)

And when you say abstract out my getting and setting, you basically mean when i pull something from redis, pass it into a function and format it how i want it correct?

**Comment by selfup** [comment]
Sorry i missed it! That split function is a life saver though!

**Comment by stevekinney** [comment]
@RickBacci Like, think about what ActiveRecord does: it connects to the database, composes the query, takes some information that is basically just rows from a table, and formats it into an object. We don't do any of that in our controller.

ActiveRecord _abstracts_ that away. At the end of the day, we just say something like `Poll.all`.

I did a _very_ basic version of this [in Idea Box](https://github.com/stevekinney/idea-box/blob/master/app/assets/javascripts/idea_repository.js) on the client. I gave myself that abstraction, and then I just had to type `Idea.all()` elsewhere in my application. Right now, if you decide to scrap using Redis, you're going to have to change _a lot_ of your application. But if you abstract it away, then you just need to change that one abstraction and you're good to go.

**Comment by rickbacci** [comment]
@stevekinney Ok thanks. i'll take a look at that. Now that I have testing working i'm thinking its a good time to refactor.

**Comment by selfup** [comment]
Yea wether you make the objects and relationships yourself or push and pull them out of a Redis, I agree on the abstraction. Make a sort of all() and find_by() function and you should be able to go either route.

**Comment by selfup** [comment]
@RickBacci I am going to a call it a night very soon. Please add me in the refactor. I want to see it! Also I will be more available tomorrow. Everything seems to be going well. You are tackling one problem at a time!

**Comment by rickbacci** [comment]
@selfup will do and thanks. pairing with Meeka tomorrow at noon, so i may stop at turing after.

**Comment by selfup** [comment]
@RickBacci Sounds good to me! Let me know how the pairing goes.

**Comment by jbrr** [comment]
That's some really good advice, Steve, I might refactor my code based on that. As of right now, I'm just planning on storing things in objects instead of a database, but that seems like just good practice. 

Anyway, good work today everyone. I'd love to see the refactor too when you're ready, @RickBacci.

**Comment by rickbacci** [comment]
@selfup yep. I think i might even write a blog post when i have mvp lol

**Comment by selfup** [comment]
@RickBacci Nice haha. Get the MVP!

**Pull request merged**
